-- Script generado automaticamente para cargar los 33 .csv a la tabla MOV_EP1_EQUIPO_09
-- Ejecutar en psql tool con: \i 'C:/datos/script_carga.sql'
-- Los CSV deben estar en C:\datos\mov

\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_pa1.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso1.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso2.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso3.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso4.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso5.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso6.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso7.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso8.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso9.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso10.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso11.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso12.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso13.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso14.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso15.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso16.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso17.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso18.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso19.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso20.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso21.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso22.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso23.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso24.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso25.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso26.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso27.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso28.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso29.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso30.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso31.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')
\copy public."MOV_EP1_EQUIPO_09" FROM 'C:/datos/mov/mov_paso32.csv' WITH (FORMAT csv, DELIMITER ';', HEADER true, ENCODING 'UTF8')


